version: '3.7'
services: 
  web:
    build: .
    image: ${PROJECT_NAME}_image
    container_name: ${PROJECT_NAME}_web
    working_dir: /confirm_rest_api
    volumes: 
      - .:/confirm_rest_api
    depends_on: 
      - db
    command: bundle exec rails s -p 80 -b '0.0.0.0'
    ports: 
      - 80:80
  db:
    image: postgres:12.1-alpine
    container_name: ${PROJECT_NAME}_db
    ports: 
      - 5432:5432
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
