version: '3.7'
services: 
  web:
    build: .
    image: web_image
    container_name: ${PROJECT_NAME}_web
    working_dir: /confirm_rest_api
    volumes: 
      - .:/confirm_rest_api
    depends_on: 
      - db
    command: ash -c '/confirm_rest_api/operation/run.sh ${PORT}'
    ports: 
      - "${PORT}:${PORT}"
  ssl_web:
    build: .
    image: web_image
    container_name: ${PROJECT_NAME}_ssl_web
    working_dir: /confirm_rest_api
    volumes: 
      - .:/confirm_rest_api
    depends_on: 
      - db
      - web
    command: ash -c '/confirm_rest_api/operation/ssl_run.sh ${SSL_PORT}'
    ports: 
      - "${SSL_PORT}:${SSL_PORT}"
  db:
    image: postgres:12.1-alpine
    container_name: ${PROJECT_NAME}_db
    ports: 
      - "5432:5432"
